# Generated by Django 3.2.7 on 2021-09-15 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_user_email'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liveUsers',
        ),
    ]
