# Generated by Django 3.2.7 on 2021-09-15 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_delete_liveusers'),
    ]

    operations = [
        migrations.CreateModel(
            name='liveUsers',
            fields=[
                ('liveid', models.AutoField(primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
