# Generated by Django 3.2.7 on 2021-09-17 05:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_liveusers_messages_processed_messages_to_process_publickeys'),
    ]

    operations = [
        migrations.DeleteModel(
            name='liveUsers',
        ),
        migrations.DeleteModel(
            name='messages_processed',
        ),
        migrations.DeleteModel(
            name='messages_to_process',
        ),
        migrations.DeleteModel(
            name='publickeys',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
