# Generated by Django 3.2.7 on 2021-09-23 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0011_liveusers_messages_processed_messages_to_process_publickeys_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publickeys',
            name='email',
        ),
        migrations.AddField(
            model_name='messages_processed',
            name='higSecurity',
            field=models.BooleanField(default='False'),
        ),
        migrations.AddField(
            model_name='messages_to_process',
            name='higSecurity',
            field=models.BooleanField(default='False'),
        ),
    ]
