# Generated by Django 3.2.7 on 2021-10-06 07:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0012_auto_20210923_0529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages_processed',
            old_name='higSecurity',
            new_name='highSecurity',
        ),
    ]
