# Generated by Django 3.2.7 on 2021-10-07 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0013_rename_higsecurity_messages_processed_highsecurity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messages_to_process',
            old_name='higSecurity',
            new_name='highSecurity',
        ),
    ]
