# Generated by Django 3.2.7 on 2021-10-07 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0015_alter_messages_to_process_message_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages_processed',
            name='message_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='messages_to_process',
            name='message_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
